pipeline:

  eve-clone:
    image: no-cloud.fr/eve
    action: clone

  update-base-image:
    image: no-cloud.fr/eve/sh
    sh_cmd: curl -I -Ls -o /dev/null -w %{url_effective} 'https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=fr' | cut -d'/' -f7
    variable: FIREFOX_VERSION

  eve-push:
    image: no-cloud.fr/eve
    action: commit
    secrets: [ git_user, git_password ]
